#include <gtest/gtest.h>

#include <cmath>
#include <memory>

#include "mesh.hpp"
#include "mfem.hpp"
#include "operator.tpp"

// --- Concrete Dummy for Testing ---
template <unsigned int... FORMS>
class DummyOp : public WhitneyFormOperator<DummyOp<FORMS...>, FORMS...>
{
public:
    using WhitneyFormOperator<DummyOp<FORMS...>, FORMS...>::WhitneyFormOperator;

    void applyDecOp(const mfem::BlockVector& in, mfem::BlockVector& out)
        const override
    {
    }
    void applyFemOp(const mfem::BlockVector& in, mfem::BlockVector& out)
        const override
    {
    }
    std::shared_ptr<mfem::SparseMatrix> assembleFem() override
    {
        return nullptr;
    }
    std::shared_ptr<mfem::SparseMatrix> assembleDec() override
    {
        return nullptr;
    }
};

// =======================================================================
//                    BLOCK STRUCTURE & SIZING TESTS
// =======================================================================

TEST(OperatorTopologyTest, BlockSizes2D_Triangular)
{
    // 2x2 Triangle Mesh (Generated by splitting Quads)
    // 9 Verts, 12 (ext) + 4 (diag) = 16 Edges, 8 Elements
    mfem::Mesh m =
        mfem::Mesh::MakeCartesian2D(2, 2, mfem::Element::TRIANGLE, true);
    auto             mesh = std::make_shared<Mesh>(std::move(m));
    DummyOp<0, 1, 2> op(mesh, BCond::Essential, OperatorMode::DEC, MassLumping::RowSum);

    EXPECT_EQ(op.getBlockSize(0), 9);
    EXPECT_EQ(op.getBlockSize(1), 16);
    EXPECT_EQ(op.getBlockSize(2), 8);

    auto bv = op.createBlockVector();
    EXPECT_EQ(bv.NumBlocks(), 3);
    EXPECT_EQ(bv.Size(), 9 + 16 + 8);
}

TEST(OperatorTopologyTest, BlockSizes3D_Tetrahedral)
{
    // 2x2x2 Tetrahedral Mesh
    mfem::Mesh m =
        mfem::Mesh::MakeCartesian3D(2, 2, 2, mfem::Element::TETRAHEDRON, true);
    auto                mesh = std::make_shared<Mesh>(std::move(m));
    DummyOp<0, 1, 2, 3> op(mesh, BCond::Natural, OperatorMode::DEC, MassLumping::RowSum);

    // Verify blocks exist and have expected dimensions for a tet mesh
    EXPECT_GT(op.getBlockSize(0), 0);  // Vertices
    EXPECT_GT(op.getBlockSize(1), 0);  // Edges
    EXPECT_GT(op.getBlockSize(2), 0);  // Faces
    EXPECT_GT(op.getBlockSize(3), 0);  // Cells (Tets)

    EXPECT_EQ(
        op.Height(), op.getBlockSize(0) + op.getBlockSize(1) +
                         op.getBlockSize(2) + op.getBlockSize(3));
}

// =======================================================================
//                    BOUNDARY ELIMINATION TESTS
// =======================================================================

TEST(BoundaryConditionTest, ExplicitColumnZeroingCheck)
{
    // Use a tetrahedral mesh for BC testing
    mfem::Mesh m =
        mfem::Mesh::MakeCartesian3D(2, 2, 2, mfem::Element::TETRAHEDRON, true);
    auto          mesh = std::make_shared<Mesh>(std::move(m));
    DummyOp<0, 1> op(mesh, BCond::Essential, OperatorMode::DEC, MassLumping::RowSum);

    const mfem::SparseMatrix& d0 = op.getExteriorDerivative(0);

    // Get the boundary DOFs for the 0-form space (Nodes)
    mfem::Array<int> bnd_dofs;
    op.getSpace(0)->GetBoundaryTrueDofs(bnd_dofs);
    ASSERT_GT(bnd_dofs.Size(), 0)
        << "Tetrahedral mesh should have boundary vertices.";

    int bnd_vtx = bnd_dofs[0];

    for (int i = 0; i < d0.Height(); ++i)
        EXPECT_EQ(d0(i, bnd_vtx), 0.0);
}

// =======================================================================
//                    EXCEPTION & SAFETY TESTS
// =======================================================================

TEST(ExceptionSafetyTest, InvalidFormRequests)
{
    mfem::Mesh m =
        mfem::Mesh::MakeCartesian3D(1, 1, 1, mfem::Element::TETRAHEDRON, true);
    auto mesh = std::make_shared<Mesh>(std::move(m));

    // Operator restricted to 0-forms and 3-forms only
    DummyOp<0, 3> op(mesh, BCond::Natural, OperatorMode::DEC, MassLumping::RowSum);

    // Check valid degrees
    EXPECT_NE(op.getSpace(0), nullptr);
    EXPECT_NE(op.getSpace(3), nullptr);

    auto bv = op.createBlockVector();

    // Valid retrieval
    EXPECT_NO_THROW(op.getFormBlock(bv, 0));
    EXPECT_NO_THROW(op.getFormBlock(bv, 3));

    // Invalid retrieval must throw
    EXPECT_THROW(op.getFormBlock(bv, 1), std::invalid_argument);
    EXPECT_THROW(op.getFormBlock(bv, 2), std::invalid_argument);
}
